# Generated by Django 4.2.8 on 2023-12-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerLoan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
